name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configuración del entorno (Node.js en este caso)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 3. Instalación de dependencias
      - name: Install dependencies
        run: npm install

      # 4. Pruebas automatizadas --------------------
      - name: Run tests
        run: npm test

      # 5. Escaneo de vulnerabilidades --------------
      - name: Scan for vulnerabilities
        run: npm audit --audit-level=high

      # 6. Construcción de la aplicación ------------
      - name: Build application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      # 7. Checkout del código nuevamente para el despliegue
      - name: Checkout code
        uses: actions/checkout@v2

      # 8. Despliegue en entorno de pruebas ----------------
      - name: Deploy to Test Environment
        run: |
          echo "Deploying to test environment..."
          # Aquí puedes agregar comandos específicos para desplegar en tu entorno de pruebas.